theme: jekyll-theme-midnight
title: "Lucinda Kraufvelin"
description: "PhD Researcher â€¢ Environmental & Marine Biology"

# navigation menu
navigation:
  - title: Home
    url: /
  - title: Illustrations
    url: /gallery

