theme: minima

# Minima's built‑in dark skin
minima:
  skin: dark

title: "Lucinda Kraufvelin"
description: "PhD Researcher • Environmental & Marine Biology"
url: "https://lukraufv.github.io"

#  pages to show in the header menu
header_pages:
  - index.md
  - gallery.md
