remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark"

title: "Lucinda Kraufvelin"
description: "PhD Researcher â€¢ Environmental & Marine Biology"
url: "https://lukraufv.github.io"

plugins:
  - jekyll-include-cache

markdown: kramdown
kramdown:
  input: GFM
